language: python
python:
  - '3.5'
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - pip install coveralls
  - pip install colorama
# Command to run tests
script: 
  - coverage run -m unittest
after_success:
  - coveralls
