language: python
python:
  - '3.5'
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - pip install coveralls
# Command to run tests
script: 
#  - coverage run --source=rpn python3 -m unittest
  - python3 -m unittest
after_success:
  - coveralls
